homeassistant:
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

hassio:

http:
  base_url: !secret base_url

camera:
  - platform: synology
    url: !secret syn_host
    username: !secret syn_name
    password: !secret syn_pass
    timeout: 15
    verify_ssl: False

  - platform: generic
    still_image_url: !secret frigate_doorbell_url
    stream_source: !secret doorbell_rtsp

discovery:

emoncms_history:
  api_key: !secret emoncms_api
  url: !secret emoncms_host
  inputnode: 19
  whitelist:
    - sensor.emon_pv_total_power
    - sensor.electricity
    - sensor.emon_measured_power

ffmpeg:

# Track calendar false is needed to prevent Hass from overwriting the google_calendar.yaml file.
google:
  client_id: !secret calendar_id
  client_secret: !secret calendar_secret
  track_new_calendar: false

ifttt:
  key: !secret ifttt_token

influxdb:
  host: !secret host
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor

input_boolean:        
  early_shift:
  late_shift:
  overtime:
  holiday:
  party:
  weekend:
  heater:
    icon: mdi:radiator
  willsbed:
  otherbed:

logger:

media_player:
  - platform: volumio
    host: Volumio-livingroom.local
    port: 3000

notify:
  - name: signal
    platform: signal_messenger
    url: !secret signal_host
    number: !secret signal_number
    recipients: # one or more recipients
      - !secret signal_recipient1

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

python_script:

stream:

# Text to speech
tts:
  - platform: marytts
    host: !secret host
    port: 59125
    codec: 'WAVE_FILE'
    voice: 'cmu-slt-hsmm'
    language: 'en_GB'
    
  - platform: google_translate
    language: 'en'

tuya:
  username: !secret user_name
  password: !secret password
  country_code: 44

unifi:
  controllers:
    - host: !secret host
      site: Default
      dont_track_devices: true
      dont_track_wired_clients: true

withings:
  client_id: !secret withings_id
  client_secret: !secret withings_secret
  profiles:
    - William

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
