homeassistant:
  # Customization file
#  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

camera:
  - platform: generic
    name: Drive
    still_image_url: !secret frigate_drive_url
    stream_source: !secret drive_rtsp

  - platform: generic
    name: Doorbell
    still_image_url: !secret frigate_doorbell_url
    stream_source: !secret doorbell_rtsp
  - platform: generic
    name: Garage
    still_image_url: !secret frigate_garage_url
    stream_source: !secret garage_rtsp

ffmpeg:

# Track calendar false is needed to prevent Hass from overwriting the google_calendar.yaml file.
google:
  client_id: !secret calendar_id
  client_secret: !secret calendar_secret
  track_new_calendar: false

hive:
  username: !secret user_name
  password: !secret hive_pass

http:
  cors_allowed_origins:
    - https://domain_name
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.xx.xx


input_boolean:
  early_shift:
  late_shift:
  overtime:
  holiday:
  party:
  weekend:
  heater:
    icon: mdi:radiator
  willsbed:
  otherbed:

notify:
  - name: signal
    platform: signal_messenger
    url: !secret signal_host
    number: !secret signal_number
    recipients: # one or more recipients
      - !secret signal_recipient1
      - !secret signal_recipient2

octopusagile:
  region_code: "E"
  mpan: MPAN
  serial: SERIAL
  auth: API_KEY
  startdate: "2020-04-25"

python_script:

recorder:
  db_url: mysql://username:password@core-mariadb/homeassistant?charset=utf8

solcast:
  api_key: !secret solcast_api
  resource_id: !secret solcast_id
  api_limit: 15

stream:

# Text to speech
tts:
  - platform: marytts
    host: !secret host
    port: 59125
    codec: 'WAVE_FILE'
    voice: 'dfki-spike-hsmm'
    language: 'en_GB'

withings:
  client_id: !secret withings_id
  client_secret: !secret withings_secret
  use_webhook: true


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
