homeassistant:
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

http:
  base_url: !secret base_url

camera:
  - platform: synology
    url: !secret syn_host
    username: !secret syn_name
    password: !secret syn_pass
    timeout: 15
    verify_ssl: False

  - name: Camera Last Person Drive
    platform: mqtt
    topic: frigate/drive/snapshot

  - name: Camera Last Person Garage
    platform: mqtt
    topic: frigate/garage/snapshot

  - name: Camera Last Person Doorbell
    platform: mqtt
    topic: frigate/doorbell/snapshot

  - platform: generic
    still_image_url: !secret frigate_doorbell_url
    stream_source: !secret doorbell_rtsp

ffmpeg:

# Track calendar false is needed to prevent Hass from overwriting the google_calendar.yaml file.
google:
  client_id: !secret calendar_id
  client_secret: !secret calendar_secret
  track_new_calendar: false

ifttt:
  key: !secret ifttt_token

input_boolean:        
  early_shift:
  late_shift:
  overtime:
  holiday:
  party:
  weekend:
  heater:
    icon: mdi:radiator
  willsbed:
  otherbed:

logger:
  default: info
  logs:
    homeassistant.components.withings: critical

media_player:
  - platform: volumio
    host: homeaudio.local
    port: 3000

notify:
  - platform: synology_chat
    name: hass_synochat
    verify_ssl: false
    resource: !secret syno_chat

python_script:

stream:

# Text to speech
tts:
  - platform: marytts
    host: !secret host
    port: 59125
    codec: 'wav'
    voice: 'cmu-slt-hsmm'
    language: 'en-US'
    
  - platform: google_translate
    language: 'en'

tuya:
  username: !secret user_name
  password: !secret tuya_pass
  country_code: 44

unifi:
  controllers:
    - host: !secret host
      site: Default
      dont_track_devices: true
      dont_track_wired_clients: true

withings:
  client_id: !secret withings_id
  client_secret: !secret withings_secret
  profiles:
    - William

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
