homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 207
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Show the introduction message on startup.
#introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: !secret base_url
#  server_port: 8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

#tuya:
#  username: !secret user_name
#  password: !secret tuya_pass
#  country_code: 44

# Track calendar false is needed to prevent Hass from overwriting the google_calendar.yaml file.
google:
  client_id: !secret calendar_id
  client_secret: !secret calendar_secret
  track_new_calendar: false

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api
  exposed_domains:
    - switch
    - light
    - group
    - vacuum

camera:
  - platform: synology
    url: !secret syn_host
    username: !secret syn_name
    password: !secret syn_pass
    timeout: 15
    verify_ssl: False

#  - platform: generic
#    name: Vacuum Map
#    still_image_url: !secret rosie_map
#    content_type: image/png
#    framerate: 1

stream:

input_boolean:        
  early_shift:
  late_shift:
  overtime:
  holiday:
  party:
  weekend:
  heater:
    icon: mdi:radiator
  willsbed:
  otherbed:

#vacuum:
#  - platform: xiaomi_miio
#    host: !secret rosie_host
#    token: !secret rosie_token
#    name: Rosie

ifttt:
  key: !secret ifttt_token

media_player:
  - platform: volumio
    host: !secret volumio_host
    port: 3000

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
