homeassistant:
  # Name of the location where Home Assistant is running
  name: Will's House
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 207
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: GB
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

http:
  ssl_certificate: /config/ssl/cert.pem
  ssl_key: /config/ssl/privkey.pem
  base_url: !secret base_url

duckdns:
  domain: !secret domain
  access_token: !secret duck_token

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

mqtt:
  broker: !secret host
  port: 1883
  keepalive: 60
  username: !secret mqtt_name
  password: !secret mqtt_pass

light:

  - platform: mqtt
    name: "KitchenCupboards"
    state_topic: "stat/sonoffKit/POWER1"
    command_topic: "cmnd/sonoffKit/POWER1"
    availability_topic: "tele/sonoffKit/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "KitchenCeiling"
    state_topic: "stat/sonoffKit/POWER2"
    command_topic: "cmnd/sonoffKit/POWER2"
    availability_topic: "tele/sonoffKit/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "HallMaster"
    state_topic: "stat/sonoffHM/POWER"
    command_topic: "cmnd/sonoffHM/POWER"
    availability_topic: "tele/sonoffHS/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "HallSlave"
    state_topic: "stat/sonoffHS/POWER"
    command_topic: "cmnd/sonoffHS/POWER"
    availability_topic: "tele/sonoffHS/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "KitchenWorktop"
    state_topic: "stat/sonoffKW/RESULT"
    state_topic: "tele/sonoffKW/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/sonoffKW/LWT"
    brightness_command_topic: "cmnd/sonoffKW/Dimmer"
    brightness_state_topic: "tele/sonoffKW/STATE"
    brightness_scale: 100
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    rgb_command_topic: "cmnd/sonoffKW/Color2"
    rgb_state_topic: "tele/sonoffKW/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/sonoffKW/Scheme"
    effect_state_topic: "tele/sonoffKW/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Kitchen Floor"
    command_topic: "cmnd/kitchenfloor/POWER"
    state_topic: "tele/kitchenfloor/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/kitchenfloor/LWT"
    brightness_command_topic: "cmnd/kitchenfloor/Dimmer"
    brightness_state_topic: "tele/kitchenfloor/STATE"
    brightness_scale: 100
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    rgb_command_topic: "cmnd/kitchenfloor/Color2"
    rgb_state_topic: "tele/kitchenfloor/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/kitchenfloor/Scheme"
    effect_state_topic: "tele/kitchenfloor/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "LivingroomMaster"
    state_topic: "stat/sonoffLM/POWER"
    command_topic: "cmnd/sonoffLM/POWER"
    availability_topic: "tele/sonoffLM/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "LivingroomSlave"
    state_topic: "stat/sonoffLS/POWER"
    command_topic: "cmnd/sonoffLS/POWER"
    availability_topic: "tele/sonoffLS/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "MasterBedroom"
    state_topic: "stat/sonoffMB/POWER"
    command_topic: "cmnd/sonoffMB/POWER"
    availability_topic: "tele/sonoffMB/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "LivingRoomWallUnit"
    state_topic: "stat/PrStrLivingRoom/POWER1"
    command_topic: "cmnd/PrStrLivingRoom/POWER1"
    availability_topic: "tele/PrStrLivingRoom/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "MasterBedroomWall"
    state_topic: "stat/MasterBedroomWall/POWER"
    command_topic: "cmnd/MasterBedroomWall/POWER"
    availability_topic: "tele/MasterBedroomWall/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

switch:

  - platform: mqtt
    name: "BedroomCurtains"
    state_topic: "stat/bedcurtain/POWER"
    command_topic: "cmnd/bedcurtain/POWER"
    availability_topic: "tele/bedcurtain/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    icon: mdi:blinds

  - platform: mqtt
    name: "LivingroomCurtains"
    state_topic: "stat/LivingroomCurtains/POWER"
    command_topic: "cmnd/LivingroomCurtains/POWER"
    availability_topic: "tele/LivingroomCurtains/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    icon: mdi:blinds

  - platform: mqtt
    name: "LivingRoomUSB"
    state_topic: "stat/PrStrLivingRoom/POWER5"
    command_topic: "cmnd/PrStrLivingRoom/POWER5"
    availability_topic: "tele/PrStrLivingRoom/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    icon: mdi:usb

#meross:
#  username: !secret user_name
#  password: !secret tuya_pass

tuya:
  username: !secret user_name
  password: !secret tuya_pass
  country_code: 44

camera:
  - platform: synology
    url: !secret syn_host
    username: !secret syn_name
    password: !secret syn_pass
    timeout: 15
    verify_ssl: False

  - platform: generic
    name: Vacuum Map
    still_image_url: !secret rosie_map
    content_type: image/png
    framerate: 1

weather:
  - platform: openweathermap
    api_key: !secret weather_key

# Track calendar false is needed to prevent Hass from overwriting the google_calendar.yaml file.
google:
  client_id: !secret calendar_id
  client_secret: !secret calendar_secret
  track_new_calendar: false

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api
  exposed_domains:
    - switch
    - light
    - group
    - vacuum

input_boolean:        
  early_shift:
  late_shift:
  overtime:
  holiday:
  party:
  weekend:
  heater:
    icon: mdi:radiator

vacuum:
  - platform: xiaomi_miio
    host: !secret rosie_host
    token: !secret rosie_token
    name: Rosie

ifttt:
  key: !secret ifttt_token

#rest_command:
#  gate_record:
#    url: !secret gate_url

media_player:
  - platform: volumio
    host: !secret volumio_host
    port: 3000

device_tracker:
#Livingroom Speaker
  - platform: googlehome
    host: !secret livingroom_speaker
    rssi_threshold: -100
    interval_seconds: 4
    consider_home: 60
    new_device_defaults:
      track_new_devices: false
#Bedroom Speaker
  - platform: googlehome
    host: !secret masterbedroom_spreaker    
    rssi_threshold: -120
    interval_seconds: 4
    consider_home: 120
    new_device_defaults:
      track_new_devices: false

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
