- platform: mqtt
  name: "SonoffBridge values"
  value_template: "{{ value_json.value }}"
  state_topic: "home/OpenMQTTGateway/SRFBtoMQTT"
  json_attributes: 
    - "raw"
    - "value"
    - "delay"
    - "val_Thigh"
    - "val_Tlow"
  qos: 1