# Trying to resolve https://community.home-assistant.io/t/sonoff-pow-used-to-limit-on-time/87299 for Mark-Mills

input_boolean:        
  shower_test:

switch:
  - platform: mqtt
    name: "Shower"
    state_topic: "stat/pow1/POWER"
    command_topic: "cmnd/pow1/POWER"
    availability_topic: "tele/pow1/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

automation:
- alias: Scrooge 
  trigger:
    platform: mqtt
    topic: "tele/pow1/SENSOR"
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.ENERGY.Power > "8" }}'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.shower_test

