esphome:
  name: "${device_name}"
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# For manual IP address setup remove each # below. manual_ip: should be 2 spaces in, the rest 4
  #manual_ip:
    #static_ip: "${device_ip}"
    #gateway: 192.168.1.1
    #subnet: 255.255.255.0

logger:
api:
  password: !secret password
ota:
  password: !secret password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay

light:
  - platform: binary
    output: status_led
    id: led

switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO12
    id: relay
    on_turn_on:
      - light.turn_on:
          id: led
    on_turn_off:
      - light.turn_off:
          id: led

output:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: yes
    id: status_led