# Sonoff 4Ch Pro R"
esphome:
  name: "${device_name}"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: "${device_ip}"
  manual_ip:
    static_ip: "${device_ip}"
    gateway: 192.168.1.1
    subnet: 255.255.255.0

logger:

api:
  password: !secret password

ota:
  password: !secret password

time:
  - platform: sntp
    id: sntp_time

# Device Specific Config
binary_sensor:
  # Push Button (Toggles Relay When Pressed)
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button 1"
    on_press:
      - light.toggle: light_1
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button 2"
    on_press:
      - light.toggle: light_2
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button 3"
    on_press:
      - light.toggle: light_3
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button 4"
    on_press:
      - light.toggle: light_4
  - platform: status
    name: "${friendly_name} Server Status"


##########
#
# GPIO2 is marked as SDA on the PCB near the top right.
# The Pads are marked as J1, I connected a 4.7k resistor between VCC and SDA  
# I then soldered the data wire of the DS18B20 onto the resistor.
#
##########

dallas:
  - pin: GPIO2

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4

light:
  - platform: binary
    name: "${friendly_name} Light Right"
    id: light_1
    output: relay_1
  - platform: binary
    name: "${friendly_name} Light Left"
    id: light_2
    output: relay_2
  - platform: binary
    name: "${friendly_name} Light 3"
    id: light_3
    output: relay_3
  - platform: binary
    name: "${friendly_name} Light 4"
    id: light_4
    output: relay_4

##########
#
# Check https://esphome.io/components/sensor/dallas.html to work out the address for the DS18B20
#
##########

sensor:
  # WiFi Signal Sensor
  - platform: wifi_signal
    name: "${friendly_name} WiFi Status"
    update_interval: 60s
  - platform: dallas
    address: 0x123xyz
    name: "Garage Temperature 1"


status_led:
  pin:
    number: GPIO13
    inverted: yes
