# Lohas RGBW GU10 Bathroom 2

# Substitutions
substitutions:
  # Device Names
  device_name: "rgbw_gu10_02"
  friendly_name: "Bathroom RGBW 2"
  device_ip: "192.168.1.x"

<<: !include common/lohas_gu10.yaml