# Replaced cheap ebay Curtain motor with proper Motorised curtain tracks using
# Dooya DT82TV and Sonoff RF Bridge with Portisch Firmware
# https://community.home-assistant.io/t/dooya-dt82tv-curtain-motors-with-sonoff-rf-bridge/97555
cover:
  - platform: mqtt
    device_class: curtain
    name: "Master Bedroom Curtains"
    command_topic: "cmnd/sonoffBridge/backlog"
    payload_open: "rfraw AA B0 35 05 08 12AC 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3A3B2B2A3A3B2B 55;rfraw off"
    payload_close: "rfraw AA B0 35 05 08 12B6 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3A3A3B2A3A3A3B 55;rfraw off"
    payload_stop: "rfraw AA B0 35 05 08 12AC 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3B2A3B2A3B2A3B 55;rfraw off"
    position_topic: "433/Master_Bedroom_Curtain"

  - platform: mqtt
    device_class: curtain
    name: "Livingroom Curtains"
    command_topic: "cmnd/sonoffBridge/backlog"
    payload_open: "rfraw AA B0 35 05 08 1324 05FA 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2B2A3A3B2B2A3A 55;rfraw off"
    payload_close: "rfraw AA B0 35 05 08 131A 05F0 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2B2B2A3B2B2B2A 55;rfraw off"
    payload_stop: "rfraw AA B0 35 05 08 132E 05FA 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2A3B2A3B2A3B2A 55;rfraw off"
    set_position_template: "50"
    position_topic: "433/Livingroom_Curtain"

# Using input_datetime to allow changing of times in front end
input_datetime:
  open_curtains_time:
    has_date: false
    has_time: true
  open_curtains_time_early:
    has_date: false
    has_time: true
  close_curtains_time:
    has_date: false
    has_time: true

sensor:
  - platform: time_date
    display_options:
      - 'time'

automation:

- id: publish_mqtt_from_master_bedroom_curtain_codes
  alias: Publish MQTT From Master Bedroom Curtain Codes
  trigger:
    - platform: mqtt
      topic: 'cmnd/sonoffBridge/backlog'
  condition:
    - condition: template
      value_template: "{{ trigger.payload in ('rfraw AA B0 35 05 08 12AC 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3A3B2B2A3A3B2B 55;rfraw off', 'rfraw AA B0 35 05 08 12B6 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3A3A3B2A3A3A3B 55;rfraw off', 'rfraw AA B0 35 05 08 12AC 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3B2A3B2A3B2A3B 55;rfraw off') }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "433/Master_Bedroom_Curtain"
        payload: >-
          {%- if trigger.payload == 'rfraw AA B0 35 05 08 12AC 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3A3B2B2A3A3B2B 55;rfraw off' -%}
            100
          {%- elif trigger.payload == 'rfraw AA B0 35 05 08 12B6 05E6 1234 1234 1234 481A3A3A3B2B2B2B2A3B2A3A3B2A3A3A3B2B2B2B2A3A3B2B2A3A3A3A3A3A3B2A3B2A3A3A3B2A3A3A3B 55;rfraw off' -%}
            0
          {%- else -%}
            50
          {%- endif -%}
        retain: True

- id: publish_mqtt_from_livingroom_curtain_codes
  alias: Publish MQTT From Livingroom Curtain Codes
  trigger:
    - platform: mqtt
      topic: 'cmnd/sonoffBridge/backlog'
  condition:
    - condition: template
      value_template: "{{ trigger.payload in ('rfraw AA B0 35 05 08 1324 05FA 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2B2A3A3B2B2A3A 55;rfraw off', 'rfraw AA B0 35 05 08 131A 05F0 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2B2B2A3B2B2B2A 55;rfraw off', 'rfraw AA B0 35 05 08 132E 05FA 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2A3B2A3B2A3B2A 55;rfraw off') }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "433/Livingroom_Curtain"
        payload: >-
          {%- if trigger.payload == 'rfraw AA B0 35 05 08 1324 05FA 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2B2A3A3B2B2A3A 55;rfraw off' -%}
            100
          {%- elif trigger.payload == 'rfraw AA B0 35 05 08 131A 05F0 1234 1234 1234 481A3B2A3A3B2B2B2A3A3B2B2A3B2B2B2B2A3A3A3B2B2A3A3B2B2B2B2B2B2A3B2A3B2B2B2A3B2B2B2A 55;rfraw off' -%}
            0
          {%- else -%}
            50
          {%- endif -%}
        retain: True

# Automation to Open and Close the curtain in the morning / evening.
- alias: Open Curtains Early
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.open_curtains_time_early.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: input_boolean.early_shift
    state: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.master_bedroom_curtains
    - delay: '00:00:01'
    - service: cover.open_cover
      entity_id: cover.livingroom_curtains

- alias: Open Curtains
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.open_curtains_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: input_boolean.early_shift
    state: 'off'
  action:
    - service: cover.open_cover
      entity_id: cover.master_bedroom_curtains
    - delay: '00:00:01'
    - service: cover.open_cover
      entity_id: cover.livingroom_curtains

- alias: Close Curtains
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.close_curtains_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    - platform: sun
      event: sunset
      # 45min before sunset
      offset: "-00:30:00"
  action:
    - service: cover.close_cover
      entity_id: cover.master_bedroom_curtains
    - delay: '00:00:01'
    - service: cover.close_cover
      entity_id: cover.livingroom_curtains