#
# inspired by https://community.home-assistant.io/t/epson-wf-3540-ink-level-monitoring/21813
#
homeassistant:
  customize:
    sensor.epson_ink_level_black:
      entity_picture:
        /local/devices/epson/ink_k.png

    sensor.epson_ink_level_magenta:
      entity_picture:
        /local/devices/epson/ink_m.png

    sensor.epson_ink_level_cyan:
      entity_picture:
        /local/devices/epson/ink_c.png

    sensor.epson_ink_level_yellow:
      entity_picture:
        /local/devices/epson/ink_y.png

    sensor.epson_waste_bin:
      entity_picture:
        /local/devices/epson/wb.png

sensor:
  - platform: command_line
    name: Epson Ink level Black
    command: /usr/bin/curl -X GET http://192.168.1.20/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 14400

  - platform: command_line
    name: Epson Ink Level Magenta
    command: /usr/bin/curl -k GET http://192.168.1.20/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 14400

  - platform: command_line
    name: Epson Ink Level Yellow
    command: /usr/bin/curl -X GET http://192.168.1.20/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 14400

  - platform: command_line
    name: Epson Ink Level Cyan
    command: /usr/bin/curl -X GET http://192.168.1.20/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 14400

  - platform: command_line
    name: Epson Waste Bin
    command: /usr/bin/curl -X GET http://192.168.1.20/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_Waste.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 14400

#Group for old interface, I use Lovelace now.
group:
  epson_printer:
    name: EPSON WF-3540
    control: hidden
    entities:
      - sensor.epson_ink_level_black
      - sensor.epson_ink_level_cyan
      - sensor.epson_ink_level_magenta
      - sensor.epson_ink_level_yellow
      - sensor.epson_waste_bin