hive:
  username: !secret user_name
  password: !secret hive_pass

#Still not working how I want.
input_select:
  heating_boost:
    name: Heating Boost
    options:
      - 00:30:00
      - 01:00:00
      - 02:00:00
      - 03:00:00
      - 04:00:00
      - None
    initial: None
    icon: mdi:radiator  
  
automation:

#If Hive gets set to 21o and above for more than 15 mins revert to normal
  - alias: Hive overtemp limit 
    trigger:
      - platform: numeric_state
        entity_id: climate.heating
        value_template: '{{ state.attributes.current_temperature }}'
        above: 21
        for:
          hours: 0
          minutes: 15
          seconds: 0
    condition:
      condition: template
      value_template: '{{ states.climate.heating.attributes.temperature > 21 }}'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 19

# Automation for variable time heating boost, uses input selects above to determin how long heating gets boosted for.
# Still not woking how I want it to.           
  - alias: "HeatBoost"
    trigger:
    # Multiple Entities for which you want to perform the same action, I am sure I can condense this down at some point.
      - platform: state
        entity_id:
          - input_select.heating_boost
        to: '00:30:00'
      - platform: state
        entity_id:
          - input_select.heating_boost
        to: '01:00:00'        
      - platform: state
        entity_id:
          - input_select.heating_boost
        to: '02:00:00'
      - platform: state
        entity_id:
          - input_select.heating_boost
        to: '03:00:00'
      - platform: state
        entity_id:
          - input_select.heating_boost
        to: '04:00:00'
        
    action:
      - service_template: climate.set_operation_mode
        data_template:
          entity_id: climate.heating
          operation_mode: 'heat'
      - service_template: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 19
      - delay: "{{ states.input_select.heating_boost.state | float }}"
      - service_template: climate.set_operation_mode
        data_template:
          entity_id: climate.heating
          operation_mode: 'auto'        
        
#############################
#                           #
# Heating - Early Shift     #
#                           #
#############################

# Automation for when to turn heating on in the mornings on early shift.
  - alias: "HeatOnMorningEarly"
    trigger:
      platform: time
      at: '04:00:00'
    condition:
      condition: state
      entity_id: input_boolean.early_shift
      state: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 19
      - delay: 00:45:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on in the afternoon on early shift.
  - alias: "HeatOnAfternoonEarly"
    trigger:
      platform: time
      at: '13:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.early_shift
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 1:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7

  # Automation for when to turn heating on in the evening on early shift.
  - alias: "HeatOnEveningEarly"
    trigger:
      platform: time
      at: '17:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.early_shift
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18.5
      - delay: 4:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7

  # Automation for when to turn heating on in the evening on early shift - Friday.
  - alias: "HeatOnAfternoonFriday"
    trigger:
      platform: time
      at: '12:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.early_shift
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
      - condition: time
        weekday:
          - fri
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 02:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  #############################
  #                           #
  # Heating - Late Shift      #
  #                           #
  #############################
  
  # Automation for when to turn heating on in the mornings on early shift.
  - alias: "HeatOnMorningLates"
    trigger:
      platform: time
      at: '07:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.late_shift
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 00:45:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on in the evening on late shift.
  - alias: "HeatOnEveningLates"
    trigger:
      platform: time
      at: '21:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.late_shift
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 00:45:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  - alias: "HeatOnEveningLatesFri"
    trigger:
      platform: time
      at: '18:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.late_shift
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
      - condition: time
        weekday:
          - fri
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 04:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  #############################
  #                           #
  # Heating - Overtime        #
  #                           #
  #############################
  
  # Automation for when to turn heating on in the mornings on overtime shift.
  - alias: "HeatOnMorningOvertime"
    trigger:
      platform: time
      at: '04:10:00'
    condition:
      - condition: state
        entity_id: input_boolean.overtime
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 00:30:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on at lunchtime at the weekend overtime.
  - alias: "HeatOnLunchOvertime"
    trigger:
      platform: time
      at: '12:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.overtime
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 01:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on in the evening on early shift.
  - alias: "HeatOnEveningOvertime"
    trigger:
      platform: time
      at: '17:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.overtime
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.outside_temperature.state < 10 }}'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18.5
      - delay: 05:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  #############################
  #                           #
  # Heating - Holiday         #
  #                           #
  #############################

  # Automation for when to turn heating on in the mornings if I am on Holiday (At Home).
  - alias: "HeatOnMorningHoliday"
    trigger:
      platform: time
      at: '07:30:00'
    condition:
      condition: state
      entity_id: input_boolean.holiday
      state: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 19
      - delay: 01:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on at lunchtime if I am on Holiday (At Home).
  - alias: "HeatOnLunchHoliday"
    trigger:
      platform: time
      at: '12:00:00'
    condition:
      condition: state
      entity_id: input_boolean.holiday
      state: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 01:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on in the evening if I am on Holiday (At Home).
  - alias: "HeatOnEveningHoliday"
    trigger:
      platform: time
      at: '17:00:00'
    condition:
      condition: state
      entity_id: input_boolean.holiday
      state: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18.5
      - delay: 06:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7  

  #############################
  #                           #
  # Heating - Party           #
  #                           #
  #############################
  
  #############################
  #                           #
  # Heating - Weekend         #
  #                           #
  #############################
  
  # Automation for when to turn heating on in the mornings at the weekend.
  - alias: "HeatOnMorningWeekend"
    trigger:
      platform: time
      at: '07:30:00'
    condition:
      condition: state
      entity_id: input_boolean.weekend
      state: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 19
      - delay: 01:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on at lunchtime at the weekend.
  - alias: "HeatOnLunchWeekend"
    trigger:
      platform: time
      at: '12:00:00'
    condition:
      condition: state
      entity_id: input_boolean.weekend
      state: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18
      - delay: 01:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  # Automation for when to turn heating on in the evening at the weekend.
  - alias: "HeatOnEveningWeekend"
    trigger:
      platform: time
      at: '17:00:00'
    condition:
      condition: state
      entity_id: input_boolean.weekend
      state: 'on'
    action:
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 18.5
      - delay: 06:00:00
      - service: climate.set_temperature
        entity_id: climate.heating
        data_template:
          temperature: 7
  
  #############################
  #                           #
  # Heating - Vacation        #
  #                           #
  #############################
  