# Octopus.Energy API
# Work in progress, Need to decide what to do with the Data!
# Based on https://community.home-assistant.io/t/templates-in-command-line-sensor-octopus-energy-api/96141

sensor:
- platform: command_line
  name: electricity
  value_template: '{{ value_json.count }}'
  scan_interval: 600
  json_attributes: 
    - results
  command: >-
    curl -u "API-Key" '"'https://api.octopus.energy/v1/electricity-meter-points/MPAN/meters/SERIAL/consumption/?period_from={{ (as_timestamp(now()) - 86400) | timestamp_custom("%Y-%m-%d", True) }}T00:00:00&period_to={{ (as_timestamp(now()) - 86400) | timestamp_custom("%Y-%m-%d", True) }}T23:59:59'"'
    
input_number:
  electricity:
    name: Electricity Use Yesterday
    icon: mdi:flash
    unit_of_measurement: 'kWh'
    min: 0
    max: 100

automation:
- alias: Electricity Update
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.electricity
      to: '48'
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.electricity
      value: '{{ (state_attr("sensor.electricity", "results") | map(attribute="consumption") | sum ) | round(3) }}'