# https://github.com/wills106/homeassistant-config/blob/master/packages/solax.yaml
# Using https://github.com/InfernoEmbedded/PowerScraper as a basis for the Modbus registers used on Solax Inverters.
# I created this as I am using the Ethernet port on the Inverter for Modnbus over TCP as the web API is unavailable.
# But the Inverter can communicate to the cloud ok somehow? I do not have a Pocket WiFi module.

modbus:
  name: SolaX
  type: tcp
  host: ip_address
  port: 502

sensor:
- platform: modbus
  scan_interval: 1
  registers:
    - name: SolaX Grid Voltage
      hub: SolaX
      unit_of_measurement: v
      register: 0
      register_type: input
      scale: 0.1
      precision: 1
    - name: SolaX Grid Current
      hub: SolaX
      unit_of_measurement: a
      register: 1
      register_type: input
      scale: 0.1
      precision: 1
    - name: Solax Inverter Power
      hub: SolaX
      unit_of_measurement: w
      register: 2
      register_type: input
    - name: SolaX PV1 Voltage
      hub: SolaX
      unit_of_measurement: v
      register: 3
      register_type: input
      scale: 0.1
      precision: 1
    - name: SolaX PV2 Voltage
      hub: SolaX
      unit_of_measurement: v
      register: 4
      register_type: input
      scale: 0.1
      precision: 1
    - name: SolaX PV1 Current
      hub: SolaX
      unit_of_measurement: a
      register: 5
      register_type: input
      offset: 1
      precision: 1
    - name: SolaX PV2 Current
      hub: SolaX
      unit_of_measurement: a
      register: 6
      register_type: input
      offset: 1
      precision: 1
    - name: SolaX Grid Frequency
      hub: SolaX
      unit_of_measurement: hz
      register: 7
      register_type: input
      scale: 0.01
      precision: 2
    - name: SolaX Inner Temp
      hub: SolaX
      unit_of_measurement: °C
      register: 8
      register_type: input
    - name: SolaX Run Mode
      hub: SolaX
      register: 9
      register_type: input
    - name: Solax PV1 Power
      hub: SolaX
      unit_of_measurement: w
      register: 10
      register_type: input
    - name: Solax PV2 Power
      hub: SolaX
      unit_of_measurement: w
      register: 11
      register_type: input
    - name: Solax Battery Voltage
      hub: SolaX
      unit_of_measurement: v
      register: 20
      register_type: input
      scale: 0.1
      precision: 1
    - name: Solax Battery Current
      hub: SolaX
      unit_of_measurement: a
      register: 21
      register_type: input
      scale: 0.1
      precision: 1
    - name: Solax Battery Power
      hub: SolaX
      unit_of_measurement: w
      register: 22
      register_type: input
    - name: Solax Charger Board Temperature
      hub: SolaX
      unit_of_measurement: °C
      register: 23
      register_type: input
    - name: Solax Charger Battery Temperature
      hub: SolaX
      unit_of_measurement: °C
      register: 24
      register_type: input
    - name: Solax Charger Boost Temperature
      hub: SolaX
      unit_of_measurement: °C
      register: 25
      register_type: input
    - name: Solax Battery Capacity
      hub: SolaX
      unit_of_measurement: "%"
      register: 28
      register_type: input
    - name: Solax Battery Energy Charged
      hub: SolaX
      unit_of_measurement: a
      register: 28
      register_type: input
    - name: Solax BMS Warning
      hub: SolaX
      register: 31
      register_type: input
    - name: Solax Battery Energy Discharged
      hub: SolaX
      unit_of_measurement: a
      register: 32
      register_type: input
    - name: Solax Battery State of Health
      hub: SolaX
      unit_of_measurement: "%"
      register: 35
      register_type: input
    - name: Solax Inverter Fault
      hub: SolaX
      register: 64
      register_type: input
    - name: Solax Charger Fault
      hub: SolaX
      register: 66
      register_type: input
    - name: Solax Manager Fault
      hub: SolaX
      register: 65
      register_type: input
    - name: SolaX Measured Power
      hub: SolaX
      unit_of_measurement: w
      register: 70
      register_type: input
    - name: SolaX Feed In Energy
      hub: SolaX
      unit_of_measurement: w
      register: 72
      register_type: input
    - name: SolaX Consumed Energy
      hub: SolaX
      unit_of_measurement: w
      register: 74
      register_type: input
    - name: SolaX EPS Voltage
      hub: SolaX
      unit_of_measurement: v
      register: 76
      register_type: input
    - name: SolaX EPS Current
      hub: SolaX
      unit_of_measurement: a
      register: 77
      register_type: input
    - name: SolaX EPS VA
      hub: SolaX
      unit_of_measurement: va
      register: 78
      register_type: input
    - name: SolaX EPS Frequency
      hub: SolaX
      unit_of_measurement: hz
      register: 79
      register_type: input
    - name: SolaX Energy Today
      hub: SolaX
      unit_of_measurement: w
      register: 80
      register_type: input
    - name: SolaX Energy Total
      hub: SolaX
      unit_of_measurement: w
      register: 82
      register_type: input
    - name: SolaX Battery Temperature
      hub: SolaX
      unit_of_measurement: °C
      register: 85
      register_type: input
    - name: SolaX Solar Energy Total
      hub: SolaX
      unit_of_measurement: w
      register: 112
      register_type: input

- platform: template
  sensors:
    powermon_totalsolar:
      friendly_name: "Solar Generation - Total"
      value_template: "{{ states('sensor.solax_pv1_power') | int + states('sensor.solax_pv2_power') | int }}"
      unit_of_measurement: 'w'
